global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth:8091"]

  - job_name: "profile-service"
    static_configs:
      - targets: ["profile:8092"]

  - job_name: "delivery-service"
    static_configs:
      - targets: ["delivery:8093"]

  - job_name: "messaging-service"
    static_configs:
      - targets: ["messaging:8094"]

  - job_name: "conversation-service"
    static_configs:
      - targets: ["conversation:8095"]

  - job_name: "presence-service"
    static_configs:
      - targets: ["presence:8096"]

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8090"]
